/**
 * Player Action Type Enum
 * Represents all possible actions a player can take during a match
 */
export enum PlayerActionType {
  DRAW_CARD = 'DRAW_CARD',
  DRAW_INITIAL_CARDS = 'DRAW_INITIAL_CARDS',
  SET_PRIZE_CARDS = 'SET_PRIZE_CARDS',
  PLAY_POKEMON = 'PLAY_POKEMON',
  SET_ACTIVE_POKEMON = 'SET_ACTIVE_POKEMON',
  ATTACH_ENERGY = 'ATTACH_ENERGY',
  PLAY_TRAINER = 'PLAY_TRAINER',
  EVOLVE_POKEMON = 'EVOLVE_POKEMON',
  RETREAT = 'RETREAT',
  ATTACK = 'ATTACK',
  USE_ABILITY = 'USE_ABILITY',
  GENERATE_COIN_FLIP = 'GENERATE_COIN_FLIP',
  SELECT_PRIZE = 'SELECT_PRIZE',
  DRAW_PRIZE = 'DRAW_PRIZE', // Alias for SELECT_PRIZE (client compatibility)
  END_TURN = 'END_TURN',
  COMPLETE_INITIAL_SETUP = 'COMPLETE_INITIAL_SETUP',
  CONFIRM_FIRST_PLAYER = 'CONFIRM_FIRST_PLAYER',
  APPROVE_MATCH = 'APPROVE_MATCH',
  CONCEDE = 'CONCEDE',
}
